name: main

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest] 

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
          if: [ "$RUNNER_OS" == "Linux" ]; then
            pylint `ls -R|grep .py$|xargs`
          if: [ "$RUNNER_OS" == "Windows" ]; then
            pylint `find . -name "*.py"`
          if [ "$RUNNER_OS" == "macOS" ]; then
            pylint `ls -R|grep .py$|xargs`
          fi
      shell: bash
    - name: Start main python file
      run: python main.py